# Generated by Django 5.0.2 on 2024-04-30 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_api', '0002_product_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='timer',
        ),
        migrations.AddField(
            model_name='product',
            name='last_bid_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
